#ifndef QXBOXCONTROLLER_GLOBAL_H
#define QXBOXCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QXBOXCONTROLLER_LIBRARY)
#  define QXBOXCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QXBOXCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QXBOXCONTROLLER_GLOBAL_H
